# Generated by Django 5.2 on 2025-05-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_violation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(max_length=100),
        ),
    ]
