# Generated by Django 5.2 on 2025-05-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_violation_app', '0003_alter_employee_staff_no_alter_vehicles_staff_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='first_vehicle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='second_vehicle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
