# Generated by Django 5.2 on 2025-05-04 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_violation_app', '0004_alter_vehicles_department_alter_vehicles_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedViolations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of violationa')),
                ('location', models.CharField(max_length=100)),
                ('plate_text', models.CharField(max_length=100)),
                ('speed', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='safety_violation_app.employee')),
            ],
        ),
    ]
