# Generated by Django 5.2 on 2025-05-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_violation_app', '0005_speedviolations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='speedviolations',
            unique_together={('employee', 'date', 'location', 'plate_text', 'speed')},
        ),
    ]
