# Generated by Django 5.2 on 2025-06-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_violation_app', '0006_alter_speedviolations_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldCameraUploadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(verbose_name='Date of Upload')),
                ('dateFrom', models.DateTimeField(verbose_name='Date & Time of First Entry in the records uploaded')),
                ('dateTo', models.DateTimeField(verbose_name='Date & Time of Last Entry in the records uploaded')),
            ],
        ),
    ]
